# Generated by Django 4.2.11 on 2024-12-02 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('instructions', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('M', 'Morning'), ('A', 'Afternoon'), ('E', 'Evening')], max_length=1)),
                ('isAfterFood', models.BooleanField(default=True)),
                ('duration', models.IntegerField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='authentication.rolebaseduser')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medication.medication')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target', to='authentication.rolebaseduser')),
            ],
        ),
        migrations.CreateModel(
            name='Intake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('period', models.CharField(choices=[('M', 'Morning'), ('A', 'Afternoon'), ('E', 'Evening')], max_length=1)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medication.medication')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.rolebaseduser')),
            ],
        ),
    ]
