# Generated by Django 4.2.11 on 2024-12-03 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intake',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
