# Generated by Django 4.2.11 on 2024-12-03 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medication', '0003_remove_intake_medication_remove_intake_patient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intake',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
