# Generated by Django 4.2.11 on 2024-12-03 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medication', '0005_remove_intake_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='intake',
            name='period',
            field=models.CharField(choices=[('M', 'Morning'), ('A', 'Afternoon'), ('E', 'Evening')], default='M', max_length=1),
        ),
    ]
